server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /colearner
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: colearner
  messages:
    encoding: UTF-8
    basename: messages/errors,messages/messages
    use-code-as-default-message: true
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/colearner}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE:10}
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL:true}
  liquibase:
    change-log: db/master.yml

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: ${LOGGING_ROOT:error}
    io.lonmstalker: ${LOGGING_PROJECT:info}
    org.hibernate: ${LOGGING_SQL:warn}

app:
  bot-token: ${BOT_TOKEN:}
  bot-username: ${BOT_USERNAME:colearner}